
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ERP.Web.Models.Database
{

using System;
    using System.Collections.Generic;
    
public partial class DM_PHU_TRACH_KH
{

    public int ID { get; set; }

    public string MA_KHACH_HANG { get; set; }

    public string SALES_PHU_TRACH { get; set; }

    public System.DateTime NGAY_BAT_DAU_PHU_TRACH { get; set; }

    public Nullable<System.DateTime> NGAY_KET_THUC_PHU_TRACH { get; set; }

    public Nullable<bool> TRANG_THAI { get; set; }



    public virtual CCTC_NHAN_VIEN CCTC_NHAN_VIEN { get; set; }

    public virtual DM_KHACH_HANG DM_KHACH_HANG { get; set; }

}

}
