
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ERP.Web.Models.Database
{

using System;
    using System.Collections.Generic;
    
public partial class MUA_HANG_HDMH
{

    public MUA_HANG_HDMH()
    {

        this.MUA_HANG_CT_HDMH = new HashSet<MUA_HANG_CT_HDMH>();

    }


    public string SO_HD { get; set; }

    public System.DateTime NGAY_HD { get; set; }

    public string KY_HIEU_HD { get; set; }

    public string MAU_SO_HD { get; set; }

    public string MA_NCC { get; set; }

    public string THAM_CHIEU { get; set; }

    public string TRUC_THUOC { get; set; }



    public virtual DM_NHA_CUNG_CAP DM_NHA_CUNG_CAP { get; set; }

    public virtual ICollection<MUA_HANG_CT_HDMH> MUA_HANG_CT_HDMH { get; set; }

}

}
